
export const PRINCIPAL_GET_REQUEST = 'PRINCIPAL_GET_REQUEST';
export const PRINCIPAL_SET_REQUEST = 'PRINCIPAL_SET_REQUEST';
export const PRINCIPAL_GET_SUCCESS = 'PRINCIPAL_GET_SUCCESS';
export const PRINCIPAL_ACTION_FAIL = 'PRINCIPAL_ACTION_FAIL';
